trigger:
  - main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: "self"
    steps:
    
    
    - task: TerraformTask@5
      displayName: Tf init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'ID'
        backendAzureRmResourceGroupName: 'Demo-resources'
        backendAzureRmStorageAccountName: 'rudraksh'
        backendAzureRmContainerName: 'tfstate-container'
        backendAzureRmKey: 'prod.terraform.tfstate'

    - task: TerraformTask@5
      displayName: Tf validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTask@5
      displayName: Tf format
      inputs:
        provider: 'azurerm'
        command: 'custom'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'ID'
        
    - task: TerraformTask@5
      displayName: Tf plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out $(Build.SourcesDirectory)/tfplanfile'
        environmentServiceNameAzureRM: 'ID'
        
    - task: ArchiveFiles@2
      displayName: Archivefiles
      inputs:
       rootFolderOrFile: '$(Build.SourcesDirectory)/'
       includeRootFolder: false
       archiveType: 'zip'
       archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'         
       replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(Build.BuildId)-build'
        publishLocation: 'Container'













    
